#!/bin/sh

# http://bhepple.freeshell.org
# http://process-getopt.sourceforge.net
# $Id: command_processor,v 1.3 2008/11/06 23:48:22 bhepple Exp $

# A test script for process-getopt - just echos options and args

check_and_process_opts() {
    local NO_OPTS TEMP PG

    PG=$(PATH=".:$PATH:$DIR"; type process-getopt |cut -d' ' -f 3)
    [ "$PG" ] || exit 1
    source $PG

    # option helper functions:
    SLOT_func() { [ "$1" ] && SLOT="yes" && echo VERBOSE=$SOPT_VERBOSE; }
    add_opt SLOT "boolean option" s "" slot 

    TOKEN_func() { [ "$1" ] && TOKEN="$2"; }
    add_opt TOKEN "option that takes a value" t n token number

    LONGONLY_func() { [ "$1" ] && LONGONLY="$2"; }
    add_opt LONGONLY "long option without short option" "" "" "long-only" "value"
    COUNTED_func() {  [ "$1" ] && (( COUNTED++ )); }
    add_opt COUNTED "an option which increments every time it is given" c

    add_std_opts # define the standard options --help etc

    TEMP=$(call_getopt "$@") || exit 1
    eval set -- "$TEMP"
    process_opts "$@"
    shift "$?"
    NEW_ARGS=( "$@" )
    return 0
}

process_add_options() {
    # option helper functions:
    clean_process_getopt
    ADDSLOT=""
    ADDSLOT_func() { [ "$1" ] && ADDSLOT="yes"; }
    add_opt ADDSLOT "boolean option" s "" add-slot 

    add_std_opts # define the standard options --help etc

    # Call getopt:
    export STOP_ON_FIRST_NON_OPT="yes"
    TEMP=$(call_getopt "$@") || exit 1
    eval set -- "$TEMP"
    process_opts "$@"; shift "$?"
    NEW_ARGS=( "$@" )
}

##########################
#         M A I N        #
##########################

PROG=$(basename $0)
DIR=$(dirname $0)
VERSION="1.0"
VERBOSE=""
ARGUMENTS="add | multiply | frob | bris [ COMMAND_OPTIONS] "
USAGE="echos options and args to stdout"

TMP="/tmp/tmp$$.tmp"
trap "/bin/rm -f $TMP" EXIT 
SLOT=""
TOKEN=""
LONGONLY=""
COUNTED=0

export STOP_ON_FIRST_NON_OPT="yes"
NEW_ARGS=( )
check_and_process_opts "$@" && set -- "${NEW_ARGS[@]}"

# At this point, all the options have been processed and removed from
# the arg list. We can now process $@ as arguments to the program.

echo "After global option processing we have:"
for i in "$@"; do echo -n " \"$i\""; done
echo

# $@ now contains only the command and its options

[ "$SLOT" ] && echo "SLOT option (-$(get_opt_letter SLOT), --$(get_opt_string SLOT))"
[ "$TOKEN" ] && echo "TOKEN option (-$(get_opt_letter TOKEN) \"$TOKEN\", --$(get_opt_string TOKEN)=\"$TOKEN\")"
[ "$LONGONLY" ] && echo "LONGONLY option (--$(get_opt_string LONGONLY)=\"$LONGONLY\")"
[ "$COUNTED" -gt 0 ] && echo "COUNTED option (-$(get_opt_letter COUNTED) = $COUNTED)"
[ "$VERBOSE" ] && echo "VERBOSE option (-$(get_opt_letter VERBOSE), --$(get_opt_string VERBOSE))"

COMMAND="$1"
shift

case $COMMAND in
    add) 
        NEW_ARGS=( )
        PROG="$PROG add"
        USAGE="do the add thing"
        process_add_options "$@"
        set -- "${NEW_ARGS[@]}"
        echo "After add option processing we have:"
        for i in "$@"; do echo -n " \"$i\""; done
        echo

        [ "$SLOT" ] && echo "SLOT option (-$(get_opt_letter SLOT), --$(get_opt_string SLOT))"
        [ "$TOKEN" ] && echo "TOKEN option (-$(get_opt_letter TOKEN) \"$TOKEN\", --$(get_opt_string TOKEN)=\"$TOKEN\")"
        [ "$LONGONLY" ] && echo "LONGONLY option (--$(get_opt_string LONGONLY)=\"$LONGONLY\")"
        [ "$COUNTED" -gt 0 ] && echo "COUNTED option (-$(get_opt_letter COUNTED) = $COUNTED)"
        [ "$VERBOSE" ] && echo "VERBOSE option (-$(get_opt_letter VERBOSE), --$(get_opt_string VERBOSE))"
        ;;
    *)
esac
