#!/bash/bash

# $Id: tiny,v 1.5 2011/07/15 18:07:13 bhepple Exp $

PROG=$(basename $0)
VERSION='$Revision: 1.5 $'
USAGE="A tiny example using process-getopt(1)"

# call process-getopt functions to define some options:
source ../../src/process-getopt || exit 1

SLOT=""
SLOT_func()   { [ "${1:-""}" ] && SLOT="yes"; }      # callback for SLOT option
add_opt SLOT "boolean option" s "" slot

TOKEN=""
TOKEN_func()  { [ "${1:-""}" ] && TOKEN="$2"; }      # callback for TOKEN option
add_opt TOKEN "this option takes a value" t n token number

add_std_opts     # define the standard options --help etc:

# The next 4 lines call the callbacks and remove the options from the
# command line so all we need to deal with in the rest of our script
# is the arguments in $@

# Re-order options and call option callbacks:
TEMP=$(call_getopt "$@") || exit 1
eval set -- "$TEMP"

# remove the options from the command line
process_opts "$@" || shift "$?"

echo "SLOT=$SLOT"
echo "TOKEN=$TOKEN"
echo "args=$@"
